version: '3.7'
networks:
  network-aplication:

services:
  db-adm:
    image: mysql:8.0
    container_name: 'mysql-adm'
    ports:
      - 3305:3306
    volumes:
      - /MysqlAdministrator/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 345678
    networks:
      - network-aplication

  db-supplier:
    image: mysql:8.0
    container_name: 'mysql-supplier'
    ports:
      - 3306:3306
    volumes:
      - /MysqlSupplier/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - network-aplication
