version: '3.7'

services:
  db-supplier:
    image: mysql:8.4
    container_name: 'mysql-supplier'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: 'SuppliersDB'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql