version: '3.7'
services:

  db:
    image: mysql:8.0
    container_name: 'mysql'
    ports:
      - 3305:3306
    volumes:
      - /mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 345678
