POST http://localhost:8080/Supplier/Register
Content-Type: application/json

{
    "name": "Daniel Silva",
    "email": "danieldanielsilva08@gmail.com",
    "address": "Rua Diamante, 986",
    "telephone": "85991850320",
    "cnpjCpf": "62613221399",
    "corporateReason": "Kumulus Tech LTDA"
}