//POST http://localhost:8080/Supplier/Register
//Content-Type: application/json

//{   
    //"name": "Daniel Silva",
    //"email": "danieldanielsilva08@gmail.com",
    //"address": "Rua Diamante, 986",
    //"telephone": "(85) 991850-320",
    //"cnpjCpf": "626.132.213-99",
    //"corporateReason": "TOTVS THECNOLOGYCAL CORPORATION"
//}

//PUT http://localhost:8080/Supplier/Edit
//Content-Type: application/json

//{   
    //"id": 29,
    //"name": "Daniel Silva",
    //"email": "danieldanielsilva08@gmail.com",
    //"address": "Rua Diamante, 986",
    //"telephone": "(85) 991850-320",
    //"cnpjCpf": "626.132.213-99",
    //"corporateReason": "TOTVS THECNOLOGYCAL CORPORATION"
//}

//GET http://localhost:8080/Supplier/SearchAll
//GET http://localhost:8080/Supplier/SearchByName/Daniel
//GET http://localhost:8080/Supplier/SearchById/29

//DELETE http://localhost:8080/Supplier/DeleteById/29